### ISSUE TITLE
New Elements - Online Resource

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#233] opened 2019-09-17 00:08 UTC
Class onlineResource 
---

New Element Definitions:
 * applicationProfile: { character} "Name of an application profile that can be used with the online resource"
 * protocolRequest: ( character ) "request used to access the resource depending on the protocol to be used (mainly for POST requests). EXAMPLE POST/XML:"
   ````xml
   <GetFeature service=”WFS” version=”2.0.0” outputFormat=”application/gml+xml; 
   version=3.2” 
   xmlns=http://www.opengis.net/wfs/2.0 
   xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance 
   xsi:schemaLocation=”http://www.opengis.net/wfs/2.0 
   http://schemas.opengis.net/wfs/2.0.0/wfs.xsd”>
   <Query typeNames=”Roads”/>
   </GetFeature>
   ````
Rules:
 - [ ] applicationProfile: optional
 - [ ] protocolRequest: optional
---

mdJson:
````json
      {
         "uri": "uri",
         "name": "online resource name",
         "description": "online resource description",
         "function": "online resource function",
         "applicationProfile": "name of application profile",
         "protocol": "protocol",
         "protocolRequest": "request used to access the resource"
      }
````

**Comment by jlblcc** [comment] 2019-09-17 00:11
This is a duplicate of #232.

**Comment by jlblcc** [comment] 2019-09-17 00:17
See also: 

https://github.com/adiwg/mdTranslator/issues/215  
https://github.com/adiwg/mdCodes/issues/29  
https://github.com/adiwg/mdEditor/issues/332

**Closed** 2019-09-20 22:18 UTC
Labels: duplicate
